projects/diw-evu%2Fdieter_public%2Fdieterpy/repository/commits: 13
projects/dlr-ve%2Fesy%2Famiris%2Famiris/issues: 12
projects/dlr-ve%2Fesy%2Famiris%2Famiris/merge_requests: 12
projects/dlr-ve%2Fesy%2Famiris%2Famiris/repository/commits: 23
projects/dlr-ve%2Fesy%2Fremix%2Fframework/repository/commits: 57
projects/energyincities%2Fpython-ehub/repository/commits: 15
projects/energyscope%2Fenergyscope/repository/commits: 4
projects/fame-framework%2Ffame-core/issues: 11
projects/fame-framework%2Ffame-core/merge_requests: 11
projects/fame-framework%2Ffame-core/merge_requests/119/notes: 2
projects/fame-framework%2Ffame-core/repository/commits: 16
projects/mosaik%2Fmosaik/issues: 12
projects/mosaik%2Fmosaik/merge_requests: 12
projects/mosaik%2Fmosaik/merge_requests/153/notes: 2
projects/mosaik%2Fmosaik/merge_requests/213/notes: 2
projects/mosaik%2Fmosaik/repository/commits: 25
projects/sesit%2Fcopper/issues: 11
projects/sesit%2Fcopper/repository/commits: 15
projects/sesit%2Fidea/repository/commits: 12
projects/sesit%2Fsilver/repository/commits: 11
projects/smartgridtoolbox%2Fsmartgridtoolbox/repository/commits: 15
projects/smspp%2Fsmspp-project/repository/commits: 28
