version = 1
SPDX-PackageName = "openmod-tracker"
SPDX-PackageSupplier = "Open Energy Transition gGmbH <info@openenergytransition.org>"
SPDX-PackageDownloadLocation = "https://github.com/open-energy-transition/openmod-tracker"

[[annotations]]
path = [
    "inventory/output/**",
    "user_analysis/output/**",
]
SPDX-FileCopyrightText = [
    "openmod-tracker contributors listed in AUTHORS.md",
]
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    "pixi.lock",
    "website/requirements.txt"
]
SPDX-FileCopyrightText = "openmod-tracker contributors listed in AUTHORS.md"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = [
    "inventory/*"
]
SPDX-FileCopyrightText = "Open Energy Transition gGmbH"
SPDX-License-Identifier = "MIT"
