# SPDX-FileCopyrightText: openmod-tracker contributors listed in AUTHORS.md
#
# SPDX-License-Identifier: CC0-1.0

name: Feature Request
description: Suggest an idea for the openmod-tracker.
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for letting us know about your idea!
  - type: textarea
    id: description
    attributes:
      label: What can be improved?
      placeholder: Tell us what you would like to see!
      value: "openmod-tracker should include building-level energy models!"
    validations:
      required: true
  - type: textarea
    id: version
    attributes:
      label: Version
      description: What version / commit hash of openmod-tracker are you using?
      placeholder: v0.1.0
    validations:
      required: true
