# SPDX-FileCopyrightText: openmod-tracker contributors
#
# SPDX-License-Identifier: CC0-1.0

name: App test CI

on:
  pull_request:
    branches:
      - main

jobs:
  serve-app:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - uses: actions/setup-python@v5.6.0
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install dependencies
        run: pip install -r website/requirements.txt pytest

      - name: Run app tests
        run: pytest tests/test_app.py
