name: Tool database and stats updater

on:
  schedule:  # runs every sunday at 10 pm
    - cron: "0 22 * * SUN"
  push: # or runs on merges into main
    branches:
      - "main"
    paths:
      - ".github/workflows/inventory-update.yml"
      - "inventory/**"
      - "!inventory/output/*.csv"

jobs:
  get-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          # For PRs, we need to fetch the full history to commit back
          fetch-depth: 0
          # Use a token that can create PRs and push to branches
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.44.0
          cache: true
          # Do not cache in branches
          cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

      - name: Get tool IDs from original stats file
        run: |
          if [[ -f "inventory/output/stats.csv" ]]; then
            tail -n +2 "inventory/output/stats.csv" | cut -d',' -f1 | sort > "ids_before.txt"
            echo "Backed up original stats.csv"
          else
            echo "No original stats.csv found"
            touch "ids_before.txt"
          fi

      - name: Run pixi task
        run: pixi run get-docs

      - name: Check for file changes
        id: check-changes
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Files have been modified by pixi task"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No files were modified by pixi task"
          fi

      - name: Check for additions/removals in stats table
        id: compare-ids
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          tail -n +2 "inventory/output/stats.csv" | cut -d',' -f1 | sort > "ids_after.txt"
          added_ids=$(comm -13 "ids_before.txt" "ids_after.txt" | tr '\n' ',' | sed 's/,$//')
          removed_ids=$(comm -23 "ids_before.txt" "ids_after.txt" | tr '\n' ',' | sed 's/,$//')

          echo "added_ids=$added_ids" >> $GITHUB_OUTPUT
          echo "removed_ids=$removed_ids" >> $GITHUB_OUTPUT

      - name: Configure Git
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # Handle changes when running on main branch
      - name: Create PR for main branch changes
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          # Delete temporary files so they don't end up in the PR
          rm -f ids_before.txt ids_after.txt

          # Create a new branch for the changes
          BRANCH_NAME="tool-stats-updates-${{ github.sha }}"
          git checkout -b $BRANCH_NAME

          # Add and commit changes
          git add .
          git commit -m "chore: update tools stats

          - **Added tools**: ${{ steps.compare-ids.outputs.added_ids }}
          - **Removed tools**: ${{ steps.compare-ids.outputs.removed_ids }}

          Auto-generated changes from pixi 'get-stats' task execution on main branch."

          # Push the new branch
          git push origin $BRANCH_NAME

          # Create PR using GitHub CLI
          gh pr create \
            --title "chore: update tools stats" \
            --body "This PR contains automated changes to the tool inventory and statistics generated by running the pixi 'get-stats' task on the main branch.

          ## Changes

          - **Added tools**: ${{ steps.compare-ids.outputs.added_ids }}
          - **Removed tools**: ${{ steps.compare-ids.outputs.removed_ids }}
          - Files were modified by pixi task execution
          - This is an automated PR created by GitHub Actions

          Please review the changes before merging." \
            --base main \
            --head $BRANCH_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Summary
        run: |
          if [[ "${{ steps.check-changes.outputs.changes }}" == "true" ]]; then
            echo "✅ Created PR with tool inventory updates"
          else
            echo "ℹ️ No changes generated by pixi task"
          fi
